accounts/urls.py
from django.urls import path

from .views import UserRegistrationView, LogoutView, UserLoginView


app_name = 'accounts'

urlpatterns = [
    path(
        "login/", UserLoginView.as_view(),
        name="user_login"
    ),
    path(
        "logout/", LogoutView.as_view(),
        name="user_logout"
    ),
    path(
        "register/", UserRegistrationView.as_view(),
        name="user_registration"
    ),
]

banking_system/urls.py
from django.contrib import admin
from django.urls import include, path

from core.views import HomeView


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path(
        'transactions/',
        include('transactions.urls', namespace='transactions')
    )
]

transactions/urls.py
from django.urls import path

from .views import financial_literacy_view, insurance_policy_view, transfer_view, loans_view, women_view, feedback_view

app_name = 'transactions'


urlpatterns = [
    path("literacy/", financial_literacy_view, name="literacy"),
    path("insurance/", insurance_policy_view, name="insurance"),
    path("transfer/", transfer_view, name="transfer"),
    path("loans/", loans_view, name="loans"),
    path("women/", women_view, name="women"),
    path("feedback/", feedback_view, name="feedback"),
]

transactions/models.py
from django.db import models

from .constants import TRANSACTION_TYPE_CHOICES
from accounts.models import UserBankAccount


class Transaction(models.Model):
    account = models.ForeignKey(
        UserBankAccount,
        related_name='transactions',
        on_delete=models.CASCADE,
    )
    amount = models.DecimalField(
        decimal_places=2,
        max_digits=12
    )
    balance_after_transaction = models.DecimalField(
        decimal_places=2,
        max_digits=12
    )
    transaction_type = models.PositiveSmallIntegerField(
        choices=TRANSACTION_TYPE_CHOICES
    )
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.account.account_no)

    class Meta:
        ordering = ['timestamp']

transactions/forms.py
import datetime

from django import forms
from django.conf import settings

from .models import Transaction

transactions/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import CreateView, ListView
from django.shortcuts import render

from transactions.models import Transaction

def financial_literacy_view(request):
       return render(request, 'transactions/literacy.html')

def insurance_policy_view(request):
       return render(request, 'transactions/insurance.html')

def transfer_view(request):
       return render(request, 'transactions/transfer.html')

def loans_view(request):
       return render(request, 'transactions/loans.html')

def women_view(request):
       return render(request, 'transactions/women.html')

def feedback_view(request):
       return render(request, 'transactions/feedback.html')

templates/transactions/insurance.html
{% extends 'core/base.html' %}

{% block content %}
  <head>
    {% load static %}
    <title>Insurance Policies</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <script>
        function showPopup() {
          const email = prompt("Please enter your email address:");
          if (email) {
            const policyNumber = prompt("Please enter your policy number:");
            alert(`Thank you! You will receive a quote shortly at ${email}.`);
          }
        }
      </script>
  </head>
  <body>
    <header>
        <h1>Farmer's Insurance</h1>
      </header>
      <main>
        <section>
          <h2>Life Insurance</h2>
          <p>Protect yourself and your families future. There are many different types of Life Insurance available. Contact your local branch or click 'Get a Quote' below to recieve further details from one of our representitives.  </p>
          <button class="quote-button" onclick="showPopup()">Get a Quote</button>
        </section>
        <section>
          <h2>Livestock Insurance</h2>
          <p>Protect your livestock from unexpected events such as theft, disease outbreaks, and accidents. Contact your local branch or click 'Get a Quote' below to recieve further details from one of our representitives.</p>
          <button class="quote-button" onclick="showPopup()">Get a Quote</button>
        </section>
        <section>
          <h2>Machinery Insurance</h2>
          <p>Protect your machinery from unexpected events such as theft, accidents, and breakdowns. Contact your local branch or click 'Get a Quote' below to recieve further details from one of our representitives.</p>
          <button class="quote-button" onclick="showPopup()">Get a Quote</button>
        </section>
      </main>
    </body>
  </html>
  {% endblock %}
      

templates/transactions/literacy.html
{% extends 'core/base.html' %}
{% block head %}
    {{ block.super }}
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles.css' %}">
{% endblock %}

{% block content %}
  <body>
    <header>

      <h1>Financial Education for Farmers</h1>
    </header>
    <main>
        <h2>Overview</h2>
        <section>
          <p>Now more than ever financial education is essential for all types of farmers to make sure they are mmanaging their money as efficently as possible. 
            At Tribal Banking we would like you to make informed decision with your finances and have provided you with the following information to help you do that:</p>
            <h3>Managing cash flow</h3>
            <p>Given the seasonal nature of farming in Ireland it is essential to manage your cashflow in a way that ensures the stability of your farm and other aspects of your life.
                Projecting income and expenses monthly is a good way to do this. Contact your local branch of click here to find out more information....
            </p>
          <h3>Borrowing</h3>
          <p>Borrowing is an essential part of farmers lifes whether you are a new or an experienced farmer. Ensuring you borrow in a way that allows you to develop as a farmer and ensure the longetivity of your farm.
            Contact your local branch of click here to find out more information....
          </p>
          <h3>Investing</h3>
          <p>If you understand investment options you can increase your wealth over time. There are many attractive investment options for farmers, ensuring you pick the right one is vital. 
            Contact your local branch of click here to find out more information....
          </p>
          <h3>Tax</h3>
          <p>Planning your tax year can help you save money and avoid penalties. Let tax not be the reason you are held back as a farmer. 
            Contact your local branch of click here to find out more information....
          </p>
        </section>
      </main>
  </html>
  {% endblock %}

templates/transactions/loans.html
{% extends 'core/base.html' %}
{% block content %}
<head>
	<title>Check Balance Page</title>
	{% load static %}
    <link rel="stylesheet" href="{% static 'transfer.css' %}">
    <script>
        function showPopup() {
          const email = alert("Loan Application has been submitted. A confirmation email will be sent to the mentioned email ID.");
        }
      </script>
</head>
<body>
  <header>
     <h1>Microloans</h1>
  </header>
    <div class="user-input">
        <label for="loanAmount">Enter loan amount:</label>
        <input type="text" id="loanAmount" name="loanAmount"><br><br><br>
        <label for="emailId">Enter email id:</label>
        <input type="text" id="emailId" name="emailId"><br><br><br>
        <label for="purpose">Enter purpose:</label>
        <input type="text" id="purpose" name="purpose"><br><br><br>
        <label for="loanYear">Years: </label>
        <input type="text" id="loanYear" name="loanYear">
        <label for="interestRate">Interest Rate:</label>
        <input type="text" id="interestRate" name="interestRate" disabled>
        <label for="loanRepayment">Total Repayment:</label>
        <input type="text" id="loanRepayment" name="loanRepayment" disabled><br><br>
        <button onclick="myFunction()" type="button" value="Proceed">Proceed</button><br><br>
        <button type="button" value="Submit" onclick="showPopup()" hidden="hidden" id="sbt_btn">Submit</button>
    </div>
    <script>
        function myFunction() {
          Loan_Amount = document.getElementById("loanAmount").value;
          Years = document.getElementById("loanYear").value;
          if(Years == 2){
            Interest_Rate = 1.5;
          }
          else if(Years == 5){
            Interest_Rate = 1.0;
          }
          else if(Years == 5){
            Interest_Rate = 1.0;
          }
          document.getElementById("interestRate").value = Interest_Rate;
          document.getElementById("loanRepayment").value = Number(Loan_Amount) + Number((Loan_Amount*Interest_Rate*Years)/100);
          document.getElementById("sbt_btn").hidden = false;
        }
        </script>
</body>
</html>
{% endblock %}

templates/transactions/transaction_form.html
{% extends 'core/base.html' %}

{% block head_title %}{{ title }}{% endblock %}

{% block content %}
<h1 class="font-mono font-bold text-3xl text-center pb-5 pt-10">{{ title }}</h1>
<hr />
<div class="w-full mt-5">
    <form method="post" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}

        <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                Amount
            </label>
            <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="amount" id="amount" type="number" required placeholder="Amount">
        </div>
        {% if form.amount.errors %}
            {% for error in form.amount.errors %}
                <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
            {% endfor %}
        {% endif %}
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
            Submit
        </button>
    </form>
</div>
{% endblock %}

templates/transactions/transaction_report.html
{% extends 'core/base.html' %}

{% block head_title %}Transaction Report{% endblock %}

{% block head_extra %}
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
{% endblock %}

{% block content %}
    <h1 class="font-mono font-bold text-3xl text-center pb-5 pt-10">Transaction Report</h1>
    <hr />
    <form method="get">
        <div class="mt-10 h-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative">
            <input type="search" name="daterange" id="search" placeholder="Filter using date range" value="{{ request.GET.daterange }}" class="appearance-none w-full outline-none focus:outline-none active:outline-none" />
            <button type="submit" class="ml-1 outline-none focus:outline-none active:outline-none">
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" class="w-6 h-6">
                    <path d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                </svg>
            </button>
        </div>
        {% if form.daterange.errors %}
            {% for error in form.daterange.errors %}
                <p class="text-red-600 text-sm italic">{{ error }}</p>
            {% endfor %}
        {% endif %}
    </form>
    <table class="table-auto mx-auto w-full mt-8">
        <thead class="bg-gray-800 text-white">
        <tr class="uppercase font-semibold text-sm">
            <th class="px-4 py-2">Transaction Type</th>
            <th class="px-4 py-2">Date</th>
            <th class="px-4 py-2">Amount</th>
            <th class="px-4 py-2">Balance After Transaction</th>
        </tr>
        </thead>
        <tbody>
        {% for transaction in object_list %}
        <tr class="{% cycle 'bg-gray-300' 'bg-white-100' %}">
            <td class="border px-4 py-2 text-center">{{ transaction.get_transaction_type_display }}</td>
            <td class="border px-4 py-2 text-center">{{ transaction.timestamp }}</td>
            <td class="border px-4 py-2 text-center">₹ {{ transaction.amount }}</td>
            <td class="border px-4 py-2 text-center">₹ {{ transaction.balance_after_transaction }}</td>
        </tr>
        {% endfor %}
        <tr class="bg-gray-600 text-white">
            <th class="px-4 py-2 text-right" colspan="3">Final Balance</th>
            <th class="px-4 py-2 text-center">₹ {{ account.balance }}</th>
        </tr>
        </tbody>
    </table>
{% endblock %}

{% block footer_extra %}
    <script type="text/javascript">
        $(function () {
            $('input[name="daterange"]').daterangepicker({
                autoUpdateInput: false,
                locale: {
                    cancelLabel: "Clear",
                },
            });

            $('input[name="daterange"]').on("apply.daterangepicker", function (ev, picker) {
                $(this).val(picker.startDate.format("YYYY-MM-DD") + " - " + picker.endDate.format("YYYY-MM-DD"));
            });

            $('input[name="daterange"]').on("cancel.daterangepicker", function (ev, picker) {
                $(this).val("");
            });
        });
    </script>
{% endblock %}

templates/transactions/transfer.html
{% extends 'core/base.html' %}

{% block content %}
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'transfer.css' %}">
    <script>
        function showPopup() {
          const email = alert("Successfully transferred !!!");
        }
      </script>
	<title>Check Balance Page</title>
</head>
<body>
  <header>
    <h1>Transfer</h1>
  </header>
    <div class="user-input">
        <label for="fromAccountNumber">Transfer from:</label>
        <input type="text" id="fromAccountNumber" name="fromAccountNumber" placeholder="Enter sender account number"><br><br>
        <label for="toAccountNumber">Transfer to:</label>
        <input type="text" id="toAccountNumber" name="toAccountNumber" placeholder="Enter receiver account number"><br><br>
        <label for="transferAmount">Amount:</label>
        <input type="text" id="transferAmount" name="transferAmount" placeholder="Enter amount"><br><br>
        <label for="transactionPassword">Password:</label>
        <input type="text" id="transactionPassword" name="transactionPassword" placeholder="Enter Transaction Password"><br><br>
        <button class="transfer-button" onclick="showPopup()">Transfer</button>
    </div>
</body>
</html>
{% endblock %}

templates/transactions/women.html
{% extends 'core/base.html' %}
{% block content %}
  <head>
    <title>Women Empowerment Scholorship</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'wom.css' %}">
    <script>
      function showPopup() {
        const email = alert("Scholorship Application has been successfully submitted.");
      }
    </script>
  </head>
  <body>
    <header>
      <h1>Women Empowerment Scholorship</h1>
    </header>
    <main>
        <h2>Women Empowerment Scholorship</h2>
        <section>
            <p>At Tribal Banking, we believe that empowering women is essential for creating a better future for all. That's why we're proud to offer our women empowerment scholarship program, designed to provide financial assistance and support to women pursuing higher education.</p>

       <p>Our scholarship program is open to women of all ages and backgrounds who are enrolled in an accredited college or university. It is based on academic merit, financial need, and demonstrated commitment to empowering women and improving their communities.
          Recipients of our women empowerment scholarships receive not only financial assistance, but also access to mentorship, networking opportunities, and other resources to support their educational and professional goals.</p>
          
        <p>If you're a woman pursuing higher education and share our commitment to empowering women, we encourage you to apply for our women empowerment scholarship program.</p>
        </section>
        <section class="sign-up">
            <p class="sign-up-para">Apply for scholorship here!</p>
            <!-- the form itself -->
            <form class="sign-up-form">
              <div class="form-input">
                <input type="text" name="first-name" id="first-name" placeholder="First Name" required>
                <span>!</span>
                <p class="warning">First name cannot be empty</p>
              </div>
      
              <div class="form-input">
                <input type="text" name="last-name" id="last-name" placeholder="Last Name" required>
                <span>!</span>
                <p class="warning">Last name cannot be empty</p>
              </div>
      
              <div class="form-input">
                <input type="number" name="Password" id="Password" placeholder="Phone" required>
                <span>!</span>
                <p class="warning">Number cannot be empty</p>
              </div>
      
              <div class="form-input">
                <input type="email" name="email" id="email" placeholder="Email Address" required>
                <span>!</span>
                <p class="warning">Looks like this is not an email</p>
              </div>
              <input class="submit-btn" button type="button" value="APPLY" onclick="showPopup()" id="sbt_btn">
            </button>
              <p class="form-term">
              </p>
            </form>
          </section>
      </main>
    </body>
  </html>
  {% endblock %}